name    'tomcat-solr'
version '0.1.0'
source 'UNKNOWN'
author 'kenorb'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'https://github.com/kenorb/tomcat-solr'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
